/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectoop;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioSystem;

/**
 *
 * @author Fuse TP
 */
public class Drum extends javax.swing.JFrame {

    /**
     * Creates new form Drum
     */
    public Drum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbC = new javax.swing.JButton();
        jbD = new javax.swing.JButton();
        jbE = new javax.swing.JButton();
        jbF = new javax.swing.JButton();
        jbG = new javax.swing.JButton();
        jbA = new javax.swing.JButton();
        jbF1 = new javax.swing.JButton();
        jbA1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jbC.setBackground(java.awt.Color.white);
        jbC.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbC.setText("C");
        jbC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCActionPerformed(evt);
            }
        });
        jbC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCKeyPressed(evt);
            }
        });

        jbD.setBackground(java.awt.Color.white);
        jbD.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbD.setText("D");
        jbD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDActionPerformed(evt);
            }
        });
        jbD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbDKeyPressed(evt);
            }
        });

        jbE.setBackground(java.awt.Color.white);
        jbE.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbE.setText("E");
        jbE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEActionPerformed(evt);
            }
        });

        jbF.setBackground(java.awt.Color.white);
        jbF.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbF.setText("F");
        jbF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFActionPerformed(evt);
            }
        });

        jbG.setBackground(java.awt.Color.white);
        jbG.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbG.setText("G");
        jbG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGActionPerformed(evt);
            }
        });

        jbA.setBackground(java.awt.Color.white);
        jbA.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbA.setText("A");
        jbA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAActionPerformed(evt);
            }
        });

        jbF1.setBackground(java.awt.Color.white);
        jbF1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbF1.setText("F1");
        jbF1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbF1ActionPerformed(evt);
            }
        });

        jbA1.setBackground(java.awt.Color.white);
        jbA1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbA1.setText("B");
        jbA1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbA1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Angsana New", 0, 48)); // NOI18N
        jButton1.setText("กลับไปยังเปียโน");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(481, 481, 481)
                .addComponent(jbA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbA1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jbE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(jbD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jbG, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jbF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(510, 510, 510)
                    .addComponent(jbF1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbA, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbA1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbC, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbE, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbD, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbG, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbF, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbF1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCActionPerformed
        playSound("C:\\Users\\Fuse TP\\Downloads\\กลอง\\กลองง\\Cymbal_1-000.WAV");
    }//GEN-LAST:event_jbCActionPerformed

    private void jbCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCKeyPressed
        // TOD:

    }//GEN-LAST:event_jbCKeyPressed

    private void jbDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDActionPerformed
        // TODO add your handling code here:
            playSound("C:\\Users\\Fuse TP\\Downloads\\กลอง\\กลองง\\Hat_1-000.WAV");
     
    }//GEN-LAST:event_jbDActionPerformed

    private void jbDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDKeyPressed

    private void jbEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEActionPerformed
        playSound("C:\\Users\\Fuse TP\\Downloads\\กลอง\\กลองง\\Kick_1-000.WAV");
    }//GEN-LAST:event_jbEActionPerformed

    private void jbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFActionPerformed
        playSound("C:\\Users\\Fuse TP\\Downloads\\กลอง\\กลองง\\Perc_1-000.WAV");

    }//GEN-LAST:event_jbFActionPerformed

    private void jbGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGActionPerformed
        playSound("C:\\Users\\Fuse TP\\Downloads\\กลอง\\กลองง\\SnareBR_2-000.WAV");
    }//GEN-LAST:event_jbGActionPerformed

    private void jbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAActionPerformed
        playSound("C:\\Users\\Fuse TP\\Downloads\\กลอง\\กลองง\\Tom_1-000.WAV");
    }//GEN-LAST:event_jbAActionPerformed

    private void jbF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbF1ActionPerformed
        playSound("C:\\Users\\Fuse TP\\Downloads\\กลอง\\กลองง\\Snare_1-000.WAV");
    }//GEN-LAST:event_jbF1ActionPerformed

    private void jbA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbA1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VirtualPiano pn = new VirtualPiano();
        pn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drum().setVisible(true);
            }
        });
    }
       public void playSound(String soundName)
 {
   try 
   {
    AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile( ));
    Clip clip = AudioSystem.getClip( );
    clip.open(audioInputStream);
    clip.start( );
   }
   catch(Exception ex)
   {
     System.out.println("Error with playing sound.");
     ex.printStackTrace( );
   }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbA;
    private javax.swing.JButton jbA1;
    private javax.swing.JButton jbC;
    private javax.swing.JButton jbD;
    private javax.swing.JButton jbE;
    private javax.swing.JButton jbF;
    private javax.swing.JButton jbF1;
    private javax.swing.JButton jbG;
    // End of variables declaration//GEN-END:variables
}
